version: '3.4'

services:
  factory-game:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    labels:
      com.centurylinklabs.watchtower.enable: "false"
